# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: taro-iconfont-svg

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.0
          run_install: true
      
      - name: Build project
        run: pnpm run build
      
      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./build/package.json
          access: public
      
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
