# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: taro-iconfont-svg

on:
  push:
    branches: 
    - main

jobs:
  publish-npm:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: ./build.sh

      - name: Publish to NPM
        run: npm publish ../build/ --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
